import { Geist, Geist_Mono } from "next/font/google";
import {NextIntlClientProvider} from 'next-intl';

import "./globals.css";
import type { Metadata } from "next";
type Props = {
  children: React.ReactNode;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TAXINET",
  description: "Generated by create next app",
  icons: {
    icon: "/aset/logo/Taxinet logo 1 6.png", // <-- make sure this file exists in public/aset/logo/
  },
};



export default async function RootLayout({children}: Props)  {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
